language: java
jdk:
  - oraclejdk8
install:
  - ./dnssd_workaround.sh
  - mvn -Ddnssd.library=`pwd`/dns_sd.jar install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn -Ddnssd.library=`pwd`/dns_sd.jar verify